Fix some minor typos and reference to "develop" branch
ONSdigital/sdc pull request #1
Opened 2017-08-23 08:32 UTC by necrophonic

- Fix spelling of "license" in readme
- Remove reference to "develop" branch in contributing

2017-09-01 08:49 UTC, ajmaddaford requested changes

2017-09-01 08:49 UTC, ajmaddaford commented on CONTRIBUTING.md
>  * You may rebase your branch after feedback if it's to include relevant updates from the develop branch. We prefer a rebase here to a merge commit as we
This line still refers to develop

2017-09-01 08:49 UTC, ajmaddaford commented on CONTRIBUTING.md
>  * You may rebase your branch after feedback if it's to include relevant updates from the develop branch. We prefer a rebase here to a merge commit as we
This still references develop rather than master

2017-09-01 08:49 UTC, ajmaddaford commented on CONTRIBUTING.md
> +* We use github-flow - create a branch from master with a short, concise, name, e.g. (nb. there are no specific prefixes):
I think we should link to http://scottchacon.com/2011/08/31/github-flow.html as it does a good job of explaining some of the reasoning behind github-flow

2017-09-04 08:00 UTC, necrophonic commented
Requested changes done

2017-09-04 08:36 UTC, ajmaddaford approved these changes

2017-09-04 12:26 UTC, merged